/******************** (C) COPYRIGHT 2011 **************************************
* File Name          : adctherm_cal.c
* Hackee             : deh
* Date First Issued  : 08/10/2011
* Board              : STM32F103VxT6_pod_mm
* Description        : Convert thermistor adc reading to degree C * 100
*******************************************************************************/
/*
A lookup table converts ADC (12b) readings for the thermistor to temperature
in degrees C * scale factor (100).

The lookup table is created using '../svn_pod/hw/trunk/eagle/ADC-ppm.c'.  This routine
saves the table in the same directory.  The output, 'adcppm.c', has been copied to
'../devices'.  Net-- screwing around with the parameters in ADC-ppm.c will not affect
the file in '../devices'.

Note: If the fixed resistor used with the thermistor is changed the table generator
must be modified and re-run.

The table only covers the useful range of temperatures.  Hence, the first entry of the
table does not correspond to a zero adc reading.  The offset value and size of the table
is generated by the table generating program.

*/

extern const unsigned short usTHERMtbloffset;		/* Lowest ADC covered by table */
extern const unsigned short usTHERMtablesize;		/* Size of table */
extern const unsigned short sTHERMtable[]; 		/* Table of temperatures * scale factor */
/******************************************************************************
 * unsigned short adctherm_cal (unsigned short usAdc);
 * @brief	: Convert adc reading to degree C * 100
 * @param	: usAdc: 12b adc reading
 * @param	: sTmpoff: temp calibration offset
 * @return	: degree C * 100
*******************************************************************************/
unsigned short adctherm_cal (unsigned short usAdc)
{
	/* Apply the offset for the table */
	int idx =  usAdc - usTHERMtbloffset;
	
	/* Be sure the index is within the table limits */
	if (idx < 0) idx = 0;
	if (idx >= usTHERMtablesize) idx = usTHERMtablesize -1;

	/* Return the temperature */
	return sTHERMtable[idx];
	
}


