#!/bin/sh
# Test scripts

BUS="$(lsusb | awk /Raisonance/ | sed -e 's/D.*$//' -e 's/Bus //' -e 's/ //')"
DEV="$(lsusb | awk /Raisonance/ | sed -e 's/:.*$//' -e 's/Bus //' -e 's/[0-9][0-9][0-9]//' -e 's/Device //' -e 's/ //')"

echo "/dev/bus/usb/$BUS/$DEV"
sudo chown $USER /dev/bus/usb/$BUS/$DEV
#ls -l /dev/bus/usb/$BUS
exit



