/******************************************************************************
* File Name          : select_function.h
* Date First Issued  : 07/15/2015
* Board              :
* Description        : Select section of database generated sections
*******************************************************************************/

//#ifndef __TENSION_IDX_V_STRUCT
//#define __TENSION_IDX_V_STRUCT

/* Select default parameters from 'idx_v_struct.h' generated by java routines. */
#define YOGURT_1		// Use parameters define for this function

/* Select using the above function, for placing command CAN IDs. */
#define CAN_UNIT_13

//#endif

