/******************************************************************************
* File Name          : tension_a_function.c
* Date First Issued  : 03/26/2015
* Board              : f103
* Description        : Tension function
*******************************************************************************/

#include <stdint.h>
#include "DTW_counter.h"
#include "yogurt_idx_v_struct.h"
#include "db/gen_db.h"
#include "yogurt_idx_v_struct.h"


/* Flash areas reserved outside of APP program flash defined in .ld file. */
extern void* __highflashlayout;	// function CMD CAN IDs table
extern void* __paramflash1;	// parameter table: Tension
extern void* __paramflash2;	// parameter table: TensionB
extern void* __paramflash3;	// parameter table: Cable_Angle

/* ========================================================================
   The following will include the structs with default parameter values and
     default command CAN IDs, as selected from the full list generated by
     the the java program from the database.  The items selected are specified
     in the "select_function.h" which is specific to this application. */
#include "select_function.h"
#include "../../../../svn_common/trunk/common_highflash.h"
#include "db/idx_v_val.c"
/* ======================================================================== */

// Parameters that go in SRAM
extern struct YOGURTTHERMS thm;	// struct with TENSION function parameters

/* **************************************************************************************
 * int yogurt_a_function_init_struct(uint32_t const* ptbl);
 * @brief	: Populate the parameter struct with the four byte parameter values
 * @param	: p = pointer to table (in flash) of parameter values
 * return	:  + = table size
 *		:  0 = error
 *		:  - = -(size of struct table count)
 * ************************************************************************************** */
static int yogurt_a_function_init_struct(uint32_t const* ptbl)
{
	uint32_t** pptr = (uint32_t**)&idx_v_ptr[0];	// Point to table of struct element pointers
	uint32_t ctr = 0;	// counter for checking size of struct vs table of values

	while (*pptr != NULL)	// Copy four byte values into struct via pointer table
	{ 
		**pptr++ = *ptbl++;
		ctr += 1;
	}
	/* struct element count versus size of table of values */
	if (ctr == 0) return ctr;
	if (ctr != (paramval[0] + 1)) return -ctr;	// Return for mismatch
	return ctr;

}
/* **************************************************************************************
 * int yogurt_a_function_init(void);
 * @brief	: Initialize
 * return	:  + = table size
 *		:  0 = error
 *		:  - = -(size of struct table count)
 * ************************************************************************************** */
int yogurt_a_function_init(void)
{
	int ret;
	/* The following is the DEFAULT values */
	ret = yogurt_a_function_init_struct(&paramval[0]);
	
	return ret;
}


