#!/bin/bash
# Builds the database from the .sql files
echo ==================================================================================================================================================================
export FLOAT_TYPE=soft
echo $FLOAT_TYPE

# Update the database
cd ../../../../svn_common/trunk/db
./db_start
echo "################## "
echo "STARTED DB SERVER"
echo "##################"

./db_updatej

# Back to original location
cd ../../../svn_sensor/sensor/co1_sensor_ublox/trunk


exit

