--
DROP TABLE CAN_UNIT;
--
CREATE TABLE CAN_UNIT 
(
CAN_UNIT_NAME varchar(32) PRIMARY KEY,
CAN_UNIT_CODE NUMERIC UNIQUE,
PROG_NAME varchar(48),
SKIP NUMERIC,
CANID_NAME varchar(48) UNIQUE,
DESCRIPTION3 varchar(128) NOT NULL UNIQUE
);


