--
DROP TABLE CANID_USED_VAL;
--
CREATE TABLE CANID_USED_VAL 
(
MSG_NAME varchar(32) NOT NULL,
FUNCTION_NAME varchar(24) NOT NULL,
FUNCTION_TYPE varchar(24) NOT NULL,
CANID_NAME varchar(32) NOT NULL,
PRIMARY KEY(FUNCTION_NAME,CANID_NAME),
DESCRIPTION varchar(128) NOT NULL
);

