-- CANID_USED_LIST.sql
-- 07/09/2015
--
-- Designate CAN IDs that are used to send readings (generally in response to a poll msg).
--
-- This table is similar to the PARAM_LIST table.  This table is needed since the CAN ID
--   hex value needs to be inserted, and that value comes from CANID table that defines the CAN ID
--   hex value for *all* CAN IDs.  
--
-- These readings are different than the ones in READINGS_LIST table which designates the
--   readings that are sent using the single command (CANID_CMD...) which designates the 
--   particular reading being sent via a byte in the payload.  The readings in the following
--   table only have one reading/reading-format per CANID
--
-- MSG_NAME for which #define <MSG_NAME <MSG_ID> (generated by java routine)
--
-- PAYLOAD_TYPE for join with CANID_USED_VAL table
--
-- FUNCTION_TYPE
--
-- A FUNCTION_TYPE can have more than one msg, but each MSG_NAME must be unique.
--
DELETE from CANID_USED_LIST;
--                                   MSG_NAME       MSG_ID    PAYLOAD_TYPE  FUNCTION_TYPE    DESCRIPTION2
INSERT INTO CANID_USED_LIST VALUES ('MSG_TENSION', 	1, 	'FF',	    'TENSION',	   	'Tension msg:  (kgf)');
INSERT INTO CANID_USED_LIST VALUES ('MSG_TIME_POLL',	2,	'U8_U8_U32','TENSION', 	 	'Tension msg: MC: Time msg/Group polling');

INSERT INTO CANID_USED_LIST VALUES ('MSG_CABLE_ANGLE',	1,  	'FF',	    'CABLE_ANGLE', 	'Cable_angle msg: cable angle (degrees)');
INSERT INTO CANID_USED_LIST VALUES ('MSG_TIME_POLL',	2,	'U8_U8_U32','CABLE_ANGLE', 	'Cable_angle msg: MC: Time msg/Group polling');


