--
DROP TABLE CANID_USED_LIST;
--
CREATE TABLE CANID_USED_LIST 
(
MSG_NAME varchar(32),
MSG_ID numeric(4),
PAYLOAD_TYPE varchar(24),
FUNCTION_TYPE varchar(24) NOT NULL,
PRIMARY KEY(MSG_NAME,FUNCTION_TYPE),
DESCRIPTION2 varchar(128) NOT NULL
);


