--
DROP TABLE CANID;
--
CREATE TABLE CANID 
(
CANID_NAME varchar(48) PRIMARY KEY,
CANID_HEX varchar(8) NOT NULL UNIQUE,
CANID_TYPE varchar(24) NOT NULL,
CAN_MSG_FMT varchar(16) NOT NULL,
DESCRIPTION varchar(128) NOT NULL UNIQUE
);


