--
DROP TABLE FUNCTION_CODES;
--
CREATE TABLE FUNCTION_CODES 
(
FUNCTION_NAME varchar(24) PRIMARY KEY,
FUNCTION_TYPE varchar(24),
CAN_UNIT_NAME varchar(24),
FUNCTION_CODE integer NOT NULL UNIQUE,
DESCRIPTION6 varchar(128) NOT NULL UNIQUE
);


