--
DROP TABLE FUNCTIONS;
--
CREATE TABLE FUNCTIONS 
(
FUNCTION_NAME varchar(24),
CANID_CMD_NAME varchar(48) NOT NULL UNIQUE,
CMD_IR varchar(1),
CAN_UNIT_NAME varchar(24) NOT NULL,
FUNCTION_TYPE varchar(24),
DESCRIPTION7 varchar(128) NOT NULL,
PRIMARY KEY(FUNCTION_NAME,CMD_IR)
);


