SELECT FUNCTIONS.CAN_UNIT_NAME, FUNCTIONS.FUNCTION_NAME, CANID.CANID_HEX
FROM CANID
  JOIN FUNCTIONS
    ON FUNCTIONS.CANID_CMD_NAME = CANID.CANID_NAME
 
;

SELECT FUNCTIONS.CAN_UNIT_NAME, FUNCTIONS.FUNCTION_NAME, FUNCTIONS.CANID_CMD_NAME, CANID.CANID_HEX
FROM CANID
  JOIN FUNCTIONS
    ON FUNCTIONS.CANID_CMD_NAME = CANID.CANID_NAME
 
;

-- CMD canids by unit name and function
SELECT FUNCTIONS.CAN_UNIT_NAME, FUNCTIONS.FUNCTION_NAME,  FUNCTIONS.CANID_CMD_NAME, CANID_HEX
FROM FUNCTIONS
  JOIN CANID
    ON CANID.CANID_NAME = FUNCTIONS.CANID_CMD_NAME
    ORDER BY CAN_UNIT_NAME DESC
;


-- List CANIDs that are not command ids, for functions by can unit, and function
SELECT FUNCTIONS.CAN_UNIT_NAME, FUNCTIONS.FUNCTION_NAME, CANID_NAME, CANID_HEX
FROM FUNCTIONS
  JOIN CANID
    ON CANID.CANID_TYPE = FUNCTIONS.FUNCTION_NAME
       AND CANID.CANID_NAME != FUNCTIONS.CANID_CMD_NAME
    ORDER BY CAN_UNIT_NAME DESC
;

-- Function Name-of-parameter Parameter-value
SELECT FUNCTIONS.FUNCTION_NAME, PARAM_NAME, PARAM_VAL, 
    CANID.CANID_HEX, PARAM_VAL.DESCRIPTION
FROM FUNCTIONS
  JOIN PARAM_VAL
    ON FUNCTIONS.CANID_CMD_NAME = PARAM_VAL.CANID_CMD_NAME
  JOIN CANID
    ON CANID.CANID_NAME = FUNCTIONS.CANID_CMD_NAME
;

-- CAN loader info
SELECT CAN_UNIT_NAME, CANID_HEX, PROG_PATH, SKIP, CAN_UNIT.DESCRIPTION 
FROM CAN_UNIT
  JOIN CANID
    ON CAN_UNIT.CANID_NAME = CANID.CANID_NAME
;
