

RUN 'CAN_UNIT_CREATE.sql';
RUN 'CAN_UNIT_INSERT.sql';

RUN 'CANID_CREATE.sql';
RUN 'CANID_INSERT.sql';

RUN 'CMD_CODES_CREATE.sql';
RUN 'CMD_CODES_INSERT.sql';

RUN 'FUNCTIONS_CREATE.sql';
RUN 'FUNCTIONS_INSERT.sql';

RUN 'FUNCTION_CODES_CREATE.sql';
RUN 'FUNCTION_CODES_INSERT.sql';

RUN 'FUNC_BIT_PARAM_CREATE.sql';
RUN 'FUNC_BIT_PARAM_INSERT.sql';

RUN 'NUMBER_TYPE_CREATE.sql';
RUN 'NUMBER_TYPE_INSERT.sql';

RUN 'PARAM_LIST_CREATE.sql';
RUN 'PARAM_LIST_INSERT.sql';

RUN 'PARAM_VAL_CREATE.sql';
RUN 'PARAM_VAL_INSERT.sql';

RUN 'PAYLOAD_TYPE_CREATE.sql';
RUN 'PAYLOAD_TYPE_INSERT.sql';

RUN 'READINGS_LIST_CREATE.sql';
RUN 'READINGS_LIST_INSERT.sql';

RUN 'CANID_USED_LIST_CREATE.sql';
RUN 'CANID_USED_LIST_INSERT.sql';

RUN 'CANID_USED_VAL_CREATE.sql';
RUN 'CANID_USED_VAL_INSERT.sql';

RUN 'PROGRAMS_CREATE.sql';
RUN 'PROGRAMS_INSERT.sql';

RUN 'SPECIFIC_FUNCS_CREATE.sql';
RUN 'SPECIFIC_FUNCS_INSERT.sql';

RUN 'SYSFUNCTIONS_CREATE.sql';
RUN 'SYSFUNCTIONS_INSERT.sql';

RUN 'FUNCTIONS_TYPE_CREATE.sql';
RUN 'FUNCTIONS_TYPE_INSERT.sql';

RUN 'WINCHSTATE_CREATE.sql';
RUN 'WINCHSTATE_INSERT.sql';

RUN 'READINGS_BOARD_CREATE.sql';
RUN 'READINGS_BOARD_INSERT.sql';

RUN 'MISC_SYS_CREATE.sql';
RUN 'MISC_SYS_INSERT.sql';


