--
DROP TABLE MISC_SYS;
--
CREATE TABLE MISC_SYS
(
MISC_SYS_NAME varchar(48) PRIMARY KEY,
MISC_SYS_VAL varchar(32) NOT NULL UNIQUE,
MISC_SYS_FMT varchar(16) NOT NULL,
DESCRIPTION_MISC_SYS varchar(128) NOT NULL UNIQUE
);


