--
DROP TABLE PARAM_VAL;
--
CREATE TABLE PARAM_VAL
(
FUNCTION_NAME varchar(24),
PARAM_NAME varchar(48),
PRIMARY KEY(FUNCTION_NAME,PARAM_NAME),
PARAM_VAL varchar(48),
FUNCTION_TYPE varchar(24) NOT NULL,
DESCRIPTION11 varchar(128) NOT NULL
);


