--
DROP TABLE PARAM_LIST;
--
CREATE TABLE PARAM_LIST 
(
PARAM_NAME varchar(48) NOT NULL,
PARAM_CODE numeric(4) NOT NULL,
TYPE_NAME varchar(24) NOT NULL,
FORMAT varchar(24) NOT NULL,
FUNCTION_TYPE varchar(24) NOT NULL,
PRIMARY KEY(FUNCTION_TYPE,PARAM_NAME),
DESCRIPTION10 varchar(128) NOT NULL UNIQUE
);


