--
DROP TABLE PAYLOAD_TYPE;
--
CREATE TABLE PAYLOAD_TYPE
(
PAYLOAD_TYPE_NAME varchar(24) PRIMARY KEY,
PAYLOAD_TYPE_CODE numeric(4) NOT NULL UNIQUE,
PAYLOAD_TYPE_DLC numeric(4) NOT NULL,
DESCRIPTION12 varchar(128) NOT NULL UNIQUE
);


