--
DROP TABLE READINGS_LIST;
--
CREATE TABLE READINGS_LIST 
(
READINGS_NAME varchar(48),
READINGS_CODE numeric(4),
TYPE_NAME varchar(24),
FORMAT varchar(24) NOT NULL,
FUNCTION_TYPE varchar(24),
DESCRIPTION16 varchar(128) NOT NULL UNIQUE,
PRIMARY KEY(READINGS_NAME,FUNCTION_TYPE)
);


