--
DROP TABLE SYSFUNCTIONS;
--
CREATE TABLE SYSFUNCTIONS
(
SYSFUNCTION_NAME varchar(24) PRIMARY KEY,
SYSFUNCTION_CODE NUMERIC UNIQUE,
GENERIC_FUNC_TYPE varchar(24),
DESCRIPTION18 varchar(128) NOT NULL UNIQUE
);


