# Makefile - Cortex-M3, STM32F103
# svn_sensor/sw_f103/trunk level
# 11-10-2012


# Current directory
SRCDIR=.

SUBDIRS =  lib
     
subdirs:
	for dir in $(SUBDIRS); do \
		$(MAKE) -C $$dir; \
	done

