/******************** (C) COPYRIGHT 2011 **************************************
* File Name          : adcppm_cal.c
* Hackee             : deh
* Date First Issued  : 08/10/2011
* Board              : STM32F103VxT6_pod_mm
* Description        : Convert thermistor adc reading to degree C * 100
*******************************************************************************/
/*
A lookup table converts ADC (12b) readings for the thermistor to 32 KHz osc error in
ppm.  This table only deals with the error versus temperature and therefore does not
include the fixed offset effor.

The table is based on the xtal spec that shows the "turnpoint" temperature a 25 deg C.
Hence, 25 deg C is zero error in this lookup table.

Note: The ppm is "negative".  Larger values mean the oscillator freq is lower than
nominal.

The lookup table is created using '../svn_pod/hw/trunk/eagle/ADC-ppm.c'.  This routine
saves the table in the same directory.  The output, 'adcthermtmp.c', has been copied to
'../devices'.  Net-- screwing around with the parameters in ADC-ppm.c will not affect
the file in '../devices'.

Note: If the fixed resistor used with the thermistor is changed the table generator
must be modified and re-run.

The table only covers the useful range of temperatures.  Hence, the first entry of the
table does not correspond to a zero adc reading.  The offset value and size of the table
is generated by the table generating program.

*/
extern const unsigned short usPPMtbloffset;	/* Lowest ADC covered by table */
extern const unsigned short usPPMtablesize;		/* Size of table */
extern const unsigned short sPPMtable[];			/* Entries of PPM * SCALE error */

/******************************************************************************
 * unsigned short adcppm_cal (unsigned short usAdc, short sCal);
 * @brief	: Convert adc reading to osc ppm error * 100
 * @param	: usAdc: 12b adc reading
 * @param	: sCal: adc adjustment for calibration 
 * @return	: ppm * 100
*******************************************************************************/
unsigned short adcppm_cal (unsigned short usAdc, short sCal)
{
	/* Apply the offset for the table */
	int idx =  (usAdc + sCal) - usPPMtbloffset;
	
	/* Be sure the index is within the table limits */
	if (idx < 0) idx = 0;
	if (idx >= usPPMtablesize) idx = usPPMtablesize -1;

	/* Return the temperature */
	return sPPMtable[idx];
	
}


