/******************** (C) COPYRIGHT 2011 **************************************
* File Name          : adctherm_cal.h
* Hackee             : deh
* Date First Issued  : 08/10/2011
* Board              : STM32F103VxT6_pod_mm
* Description        : Convert thermistor adc reading to degree C * 100
*******************************************************************************/
/*
Note: If the fixed resistor used with the thermistor is changed the table generator
must be modified and re-run.

The table only covers the useful range of temperatures.  Hence, the first entry of the
table does not correspond to a zero adc reading.  The offset value and size of the table
is generated by the table generating program.

When the ADC reading exceeds the table limits the highest or lowest converted value
is returned.

*/

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ADCPPM_CAL
#define __ADCPPM_CAL

/******************************************************************************/
unsigned short adcppm_cal (unsigned short usAdc, short sCal);
/* @brief	: Convert adc reading to osc ppm error * 100
 * @param	: usAdc: 12b adc reading
 * @param	: sCal: adc adjustment for calibration 
 * @return	: ppm * 100
*******************************************************************************/



#endif 

