C compile: gfortran polrgdeh.for multr.for minv.for order.for gdata.for -o polrgdeh

C        SAMPLE MAIN PROGRAM FOR POLYNOMIAL REGRESSION - POLRG
        IMPLICIT DOUBLE PRECISION (A - H)
        IMPLICIT DOUBLE PRECISION (O - Z)
C  THE FOLLOWING ROUTINES ARE USED: GDATA,ORDER,MINV,MULTR
C       AND AN OPTIONAL PLOTTING SUBROUTINE COULD BE ADDED
C
C       THE FOLLOWING DIMENSION MUST BE GREATER THAN OR EQUAL TO THE
C       PRODUCT OF N*(M+1) WHERE N IS THE NUMBER OF OBSERVATIONS AND
C       M IS THE HIGHEST DEGREE POLYNOMIAL SPECIFIED.
C	N = 100 observations; M = 6
        DIMENSION X(15000)
C       THE FOLLOWING DIMENSION MUST BE GREATER THAN OR EQUAL TO THE
C       PRODUCT OF M*M.
        DIMENSION DI(100)
C       THE FOLLOWING DIMENSION MUST BE GREATER THAN OR EQUAL TO
C       (M+2)*(M+1)/2.
        DIMENSION D(100)
C       THE FOLLOWING DIMENSIONS MUST BE GREATER THAN OR EQUAL TO M.
        DIMENSION B(6),SB(6),T(6),E(6)
C       THE FOLLOWING DIMENSIONS MUST BE GREATER THAN OR EQUAL TO
C       (M+1).
        DIMENSION XBAR(7),STD(7),COE(7),SUMSQ(7),ISAVE(7)
C       THE FOLLOWING DIMENSION MUST BE GREATER THAN OR EQUAL TO 10.
        DIMENSION ANS(20)
C
	CHARACTER P*6
	CHARACTER FILEI*20
	CHARACTER FILEO*20
C       OUTPUT CHANNEL = IOUT, INPUT CHANNEL = IN
C	RULER FOR COLUMNS 1-72
CCCCCCCCCC..........//////////..........//////////..........//////////ZZ
C		LOGICAL DEVICE FOR READ, WRITE


C	WRITE (*,92)
C92	FORMAT (' Enter input file name'/)
C	READ (*,*) FILEI
	IN = 10
C	OPEN (unit=IN,file=FILEI,status='old')
	OPEN (unit=IN,file='polgdegA.dat',status='old')

	WRITE (*,93)
93	FORMAT (' Enter 6 char output file name'/)
	READ (*,*) FILEO
	IOUT = 2
	OPEN (unit=IOUT,file=FILEO,status='new')



C	Read format for input data
C       READ PARAMETER CARD
100     READ(IN,*) P,N,M
C       P=PROBLEM NUMBER (MAY BE ALPHAMERIC)
C       N=NUMBER OF OBSERVATIONS
C       M=HIGHEST DEGREE POLYNOMIAL SPECIFIED
C
        IF(N.EQ.0) STOP
C
C       PRINT PROBLEM NUMBER AND N.
        WRITE(IOUT,3) P
3       FORMAT(//27H POLYNOMIAL REGRESSION.....,A6)
        WRITE(IOUT,4) N,M
4       FORMAT(/23H NUMBER OF OBSERVATION,I4/' HIGHEST DEGREE',I4)
C
C       READ INPUT DATA
        L=N*M
        DO 110 I=1,N
        J=L+I
C       X(I) IS THE INDEPENDENT VARIABLE, AND X(J) IS THE DEPENDENT
C       VARIABLE.
        READ(IN,*) X(I),X(J)
	WRITE (IOUT,*) X(I),X(J)
  110   CONTINUE
        CALL GDATA(N,M,X,XBAR,STD,D,SUMSQ)
        MM=M+1
        SUM=0.0
        NT=N-1
        DO 200 I=1,M
        ISAVE(I)=I
C       FORM SUBSET OF CORRELATION COEFFICIENT MATRIX
        CALL ORDER(M,D,MM,I,ISAVE,DI,E)
C       INVERT THE SUBMATRIX OF CORRELATION COEFFICIENTS
        CALL MINV(DI,I,DET,B,T)
232     CALL MULTR(N,I,XBAR,STD,SUMSQ,DI,E,ISAVE,B,SB,T,ANS)
C
C       PRINT THE RESULT OF CALCULATION
        WRITE(IOUT,5) I
5       FORMAT(/32H POLYNOMIAL REGRESSION OF DEGREE,I3)
        IF(ANS(7)) 140,130,130
130     SUMIP=ANS(4)-SUM
        IF(SUMIP) 140,140,150
140     WRITE(IOUT,13)
13      FORMAT(/17H  NO IMPROVEMENT )
        GO TO 100
150     WRITE(IOUT,6) ANS(1)
6       FORMAT(/'C-----   INTERCEPT'/'      DATA RCPT/',D26.16,'/')
        WRITE(IOUT,7) (J,B(J),J=1,I)
7       FORMAT(/'C-----   REGRESSION COEFFICIENTS'/
     1 ('      DATA D(',I1,') /',D26.16,'/'))
        WRITE(IOUT,8) I
8         FORMAT(/8X,24HANALYSIS OF VARIANCE FOR,I4,19H  DEGREE POLYNOMI
     1AL/)
        WRITE(IOUT,9)
9         FORMAT(/' SOURCE OF VARIATION  DEGREE'6X'SUM OF'8X'MEAN'
     110X'F    IMPROVEMENT'/24X'OF'8X'SQUARES'7X'SQUARE'6X
     2'VALUE  IN TERMS OF'/21X'FREEDOM'39X'SUM OF SQUARE')
        SUM=ANS(4)
        WRITE(IOUT,10) I,ANS(4),ANS(6),ANS(10),SUMIP
10      FORMAT(/' DUE TO REGRESSION',I6,4X,4F13.5)
        NI=ANS(8)
        WRITE(IOUT,11) NI,ANS(7),ANS(9)
11      FORMAT(' DEVIATION ABOUT'/8X'REGRESSION',I6,4X,2F13.5)
        WRITE(IOUT,12) NT,SUMSQ(MM)
12      FORMAT(' TOTAL',12X,I6,4X,F13.5///)
200     CONTINUE
        END

