#!/bin/bash
# portfwd-w-netbook
# Start port forwarding with connection to netbook
# 03-04-2014

# Usage: hub-w-netbook localportused 

# Default port
PT=32123

# arg 1 = localhost port on this machine (32123 default)
if [ $# -gt 1 ] ; then
	echo "Only one argument allowed, e.g."
	echo "hub-w-netbook 32140"
	exit	
fi

# Substitute command line port number
if [ $# -eq 1 ] ; then
	PT=$1
fi

echo "LOCALPORT TO BE USED IS $PT" # Let the hapless OP know what is going on

# By-pass setting up the port forwarding the port is already present
nc -z localhost $PT; XA=`echo $?`
if [ $XA -ne 0 ] ; then
	echo "Starting port forwarding to netbook--command being executed is:"
	echo "    ssh -T -L$PT:127.0.0.1:32123 -p 41576 hub-server@$FITIP"
	ssh -T -L$PT:127.0.0.1:32123 -p 41576 hub-server@$FITIP &



# One second loop if localhost port is present
XA=1
CTR=0
while [ $XA -ne 0 ]
do 
	nc -z localhost $PT
	XA=`echo $?`
	if [ $XA -ne 0 ] ; then
		echo "$CTR Waiting for connect on port $PT"
		CTR=`expr $CTR + 1`
		sleep 1
	fi
done

else
	echo "PORT $PT is already present so a ssh port forward was not started"
fi


echo "SUCCESS.  PORT $PT IS PRESENT"
echo
echo "The following command will start a netcat terminal"
echo "nc localhost $PT"
echo



