#!/bin/bash
#
# command line
# socat_client <uart device>
# Examples--
# socat_server /dev/ttyUSB0
# socat_server /dev/ttyUSB3
# socat_server /dev/ttyACM0
#
# socat   connect ip:port  FILE:device,baud rate, raw, no echo, & = background
socat TCP4:localhost:32123,nodelay FILE:$1,b230400,raw,echo=0,crtscts=0 &

exit
