#!/bin/bash
# 09/08/2016
# Compile and load database parameter tables
# ./mm <table selection name first function>
# ./mm 
# 
# Specify which flash size
export LDRAPPLD=ldrapp_VE.ld

echo
echo "########## First table $1"
make -f Makefile clean
make -f Makefile TSELECT=-D$1 && make -f Makefile TSELECT=-D$1 flash

echo
echo "########## Table with function command CAN ids $2"
make -f Makefile_unit clean
make -f Makefile_unit TSELECT=-D$2 && make -f Makefile_unit TSELECT=-D$2 flash

