/******************************************************************************
* File Name          : tension_a_function.c
* Date First Issued  : 03/26/2015
* Board              : f103
* Description        : Tension function
*******************************************************************************/

#include "tension_function.h"
#include "can_hub.h"
#include "db/gen_db.h"

/* Pointer to APP, function-specific canids, generated by linker, specified in .ld file. */
extern void* __highflashlayout;

// Tension parameters that go in SRAM
struct TENSIONLC ten;	// Tension parameters

/* "Consumer" tension struct pointer -- SRAM */
struct TENSIONLC* pten = &ten;	// Initially point to the sram struct

static struct CANRCVBUF can_measurement;	// Msg in response to group poll

static uint32_t	canid_cmd = CANID_CMD_TENSION_1;	// Function command can id (default) 

static struct CANHUB* phub_tension;

static u32 hb_t;	// Next DTWTIIME for heart-beat
static struct CANRCVBUF can_hb = {HEARTBEATTICKS_TENSION1};

/* Easy way for other routines to access via 'extern'*/
extern struct CAN_CTLBLOCK* pctl1;

/* Last good 24 bit reading, bipolar, zero offset adjusted */
extern volatile int		ad7799_ten_last_good_reading;	

/* **************************************************************************************
 * static send_can_cmd(struct CANRCVBUF* pcan, int32_t v); 
 * @brief	: Setup DLC and payload for sending a current reading
 * @param	: Pointer to incoming CAN msg that has "readings" command
 * @param	: v = 4 byte value to be sent
 * ************************************************************************************** */
static send_can(struct CANRCVBUF* pcan, int32_t v)
{
	pcan->dlc = 6;			// Set return msg payload count
	pcan->cd.uc[3] = (v >>  0);	// Add 4 byte value to payload
	pcan->cd.uc[4] = (v >>  8);
	pcan->cd.uc[5] = (v >> 16);
	pcan->cd.uc[6] = (v >> 24);
	can_hub_send(pcan, phub_tension);// Send CAN msg
	hb_t = DTWTIME + pten->hb_ct;	// Reset heart-beat time each time msg sent
	return;
}

/* **************************************************************************************
 * void tension_poll_init(void);
 * @brief	: Initialize
 * ************************************************************************************** */
void tension_a_function_init(void)
{
	int i;

	phub_tension    = can_hub_add_func();	// Set up port/connection to can_hub

	tension_param_default_init(pten);	// Setup default values

	/* Replace default command canid with one from table for this function instance. */
	struct HIGHFLASHH* phfl = (struct HIGHFLASHH*)&__highflashlayout;
	for (i = 0; i < HIGHFLASHHTABLESIZE; i++)
	{
		if (phfl->tbl[i].function_code == FUNCTION_CODE_TENSION)
		{ // Here, we found our command can id!
			canid_cmd = phfl->tbl[i].canid;
		}
		/* Check if we ran into erased flash. */
		if (phfl->tbl[i].function_code == ~0) break;
	}
	
	return;
}
/* **************************************************************************************
 * void tension_function_poll(CANRCVBUF* pcan);
 * @brief	: Handle incoming CAN msgs
 * @param	; pcan = pointer to CAN msg buffer
 * @return	: Nothing for the nonce
 * ************************************************************************************** */
void tension_function_poll(struct CANRCVBUF* pcan)
{
	/* Check for AD7799 reading ready and filter. */
	ad7799_poll_rdy_ten();

	/* Check for group poll. */
	if (pcan->id == pten->canid_drum_poll)
	{ // Here, group poll msg.  Check if our drum system is included
		if ((pcan->cd.uc[0] & POLL_FUNC_BIT_TENSION) != 0)
		{ // Here, yes.  See if our function is included
			if ((pcan->cd.uc[0] & POLL_FUNC_BIT_TENSION) != 0)
			{ // Here, yes.  Send our precious msg.
				pcan->cd.uc[0] = 0;	// Status
				send_can(pcan, ad7799_ten_last_good_reading);
				return;
			}
		}
		return;
	}
	
	/* Check for command. */
	if (pcan->id == canid_cmd)
	{ // Here, we have a command msg for this function instance. 
		// handle command code
	}

	/* Check for need to send  heart-beat. */
	 if ( ((int)DTWTIME - (int)hb_t) > 0  );	// Time to send heart-beat
	{
		send_can(&can_hb, ad7799_ten_last_good_reading);
		hb_t = DTWTIME + pten->hb_ct;	// Reset heart-beat time each time msg sent
	}
	return;
}
