#!/bin/bash
# plot_mmag_seplist
# Run through list doing mmag_plotR for the list of individual 'R files
# Example: ./plot_mmag_seplist 0
# Where arg 1 = option (0-3)
#         '0': // Tension only
#         '1': // Tension and GPS
#         '2': // Tension and Accelerometer
#         '3': // Tension, GPS, Accelerometer

# Make sure correct number of arguments
# If no argument supplied setup a default USB port
if [ $# -ne 1 ] ; then
	echo "One argument required, e.g. ./plot_mmag_seplist 0"
	echo "  where 1st = data code--"
	echo "            0 = tension only"
	echo "            1 = tension and gps"
	echo "            2 = tension and accelerometer"
	echo "            3 = tension, accelerometer, and gps"
	exit	
fi

DIR=$HOME/svn_pod/sw_PC/trunk/helper
FILELIST="\
sep.001R \
sep.002R \
sep.003R \
sep.004R \
sep.005R \
sep.006R \
sep.007R \
sep.008R \
sep.009R \
sep.010R \
sep.011R \
sep.012R \
sep.013R \
sep.014R \
sep.015R \
sep.016R \
sep.017R \
sep.018R \
sep.019R \
sep.020R \
sep.021R \
sep.022R \
"

for FILENAME in $FILELIST
do
#	echo $FILENAME
	mmag_plotR $DIR $FILENAME $1
done
