#!/bin/bash
# plot_mmag_setlist
# Run through list doing mmag_plotR for the list of individual 'R files
# Example: ./plot_mmag_130106list 0
# Where arg 1 = option (0-3)
#         '0': // Tension only
#         '1': // Tension and GPS
#         '2': // Tension and Accelerometer
#         '3': // Tension, GPS, Accelerometer

# Make sure correct number of arguments
# If no argument supplied setup a default USB port
if [ $# -ne 1 ] ; then
	echo "One argument required, e.g. ./plot_mmag_130106list 0"
	echo "  where 1st = data code--"
	echo "            0 = tension only"
	echo "            1 = tension and gps"
	echo "            2 = tension and accelerometer"
	echo "            3 = tension, accelerometer, and gps"
	exit	
fi

DIR=$HOME/svn_pod/sw_PC/trunk/helper
FILELIST="\
130106.183442R \
130106.181720R \
130106.175715R \
130106.174731R \
130106.173714R \
130106.172256R \
"

for FILENAME in $FILELIST
do
#	echo $FILENAME
	mmag_plotR $DIR $FILENAME $1
done
